MOODS = ["adventure", "relaxation", "culture", "food", "nature", "romance", "nightlife"]

ASSISTANT_AREAS = ["Europe", "North America", "South America", "Japan", "Islands"]

DESTINATIONS = [
    {
        "id": 1,
        "name": "Santorini",
        "region": "Greece",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["beach", "romance", "food"],
        "moods": ["romance", "relaxation", "food"],
        "avg_cost_per_day": 140,
        "description": "Whitewashed villages and sunsets that look unreal.",
    },
    {
        "id": 2,
        "name": "Kyoto",
        "region": "Japan",
        "area": "Japan",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["culture", "history", "food"],
        "moods": ["culture", "nature", "food"],
        "avg_cost_per_day": 120,
        "description": "Temples, tea houses, and cherry blossoms.",
    },
    {
        "id": 3,
        "name": "Marrakech",
        "region": "Morocco",
        "area": "Africa",
        "budget_level": "low",
        "climate": "desert",
        "tags": ["market", "spa", "adventure"],
        "moods": ["culture", "adventure", "relaxation"],
        "avg_cost_per_day": 90,
        "description": "Souks, riads, and the golden desert on the doorstep.",
    },
    {
        "id": 4,
        "name": "Reykjavik",
        "region": "Iceland",
        "area": "Europe",
        "budget_level": "high",
        "climate": "cool",
        "tags": ["nature", "northern-lights", "road-trip"],
        "moods": ["nature", "adventure"],
        "avg_cost_per_day": 180,
        "description": "Hot springs, glaciers, and northern lights.",
    },
    {
        "id": 5,
        "name": "Bali",
        "region": "Indonesia",
        "area": "Islands",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["beach", "wellness", "relaxation"],
        "moods": ["relaxation", "nature", "beach"],
        "avg_cost_per_day": 80,
        "description": "Rice terraces, surf, and slow island mornings.",
    },
    {
        "id": 6,
        "name": "Lisbon",
        "region": "Portugal",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["food", "culture", "beach"],
        "moods": ["culture", "food", "relaxation"],
        "avg_cost_per_day": 110,
        "description": "Tram rides, pastel de nata, and Atlantic sunsets.",
    },
    {
        "id": 7,
        "name": "Queenstown",
        "region": "New Zealand",
        "area": "Oceania",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["adventure", "nature", "road-trip"],
        "moods": ["adventure", "nature"],
        "avg_cost_per_day": 170,
        "description": "Bungee jumping capital with epic mountain lakes.",
    },
    {
        "id": 8,
        "name": "Hanoi",
        "region": "Vietnam",
        "area": "Asia",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["food", "history", "market"],
        "moods": ["food", "culture"],
        "avg_cost_per_day": 55,
        "description": "Street food, lakes, and a hundred-year-old old town.",
    },
    {
        "id": 9,
        "name": "Paris",
        "region": "France",
        "area": "Europe",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["culture", "romance", "food"],
        "moods": ["romance", "culture", "food"],
        "avg_cost_per_day": 160,
        "description": "Cafés, boulevards, and the Eiffel Tower.",
    },
    {
        "id": 10,
        "name": "Rome",
        "region": "Italy",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["history", "culture", "food"],
        "moods": ["culture", "history", "food"],
        "avg_cost_per_day": 120,
        "description": "Two thousand years of history on every corner.",
    },
    {
        "id": 11,
        "name": "Interlaken",
        "region": "Switzerland",
        "area": "Europe",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["mountains", "adventure", "nature"],
        "moods": ["adventure", "nature"],
        "avg_cost_per_day": 200,
        "description": "Alpine trails between two turquoise lakes.",
    },
    {
        "id": 12,
        "name": "Barcelona",
        "region": "Spain",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["culture", "food", "beach"],
        "moods": ["culture", "nightlife", "food"],
        "avg_cost_per_day": 130,
        "description": "Gaudí, tapas, and a beach in the city centre.",
    },
    {
        "id": 13,
        "name": "Amsterdam",
        "region": "Netherlands",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["culture", "history", "food"],
        "moods": ["culture", "nightlife", "food"],
        "avg_cost_per_day": 125,
        "description": "Canals, bikes, and world-class museums.",
    },
    {
        "id": 14,
        "name": "New York",
        "region": "USA",
        "area": "North America",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["culture", "food", "nightlife"],
        "moods": ["culture", "nightlife", "food"],
        "avg_cost_per_day": 170,
        "description": "The city that never sleeps — Broadway to Brooklyn.",
    },
    {
        "id": 15,
        "name": "Cancun",
        "region": "Mexico",
        "area": "North America",
        "budget_level": "mid",
        "climate": "tropical",
        "tags": ["beach", "relaxation", "nightlife"],
        "moods": ["relaxation", "nightlife", "beach"],
        "avg_cost_per_day": 110,
        "description": "Caribbean beaches and ancient ruins nearby.",
    },
    {
        "id": 16,
        "name": "Vancouver",
        "region": "Canada",
        "area": "North America",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["nature", "mountains", "food"],
        "moods": ["nature", "adventure", "food"],
        "avg_cost_per_day": 160,
        "description": "Ocean, forest, and mountains in one skyline.",
    },
    {
        "id": 17,
        "name": "Rio de Janeiro",
        "region": "Brazil",
        "area": "South America",
        "budget_level": "mid",
        "climate": "tropical",
        "tags": ["beach", "nightlife", "nature"],
        "moods": ["nightlife", "beach", "nature"],
        "avg_cost_per_day": 120,
        "description": "Samba, sugarloaf, and Copacabana.",
    },
    {
        "id": 18,
        "name": "Cusco",
        "region": "Peru",
        "area": "South America",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["history", "adventure", "culture"],
        "moods": ["adventure", "culture", "history"],
        "avg_cost_per_day": 100,
        "description": "Gateway to Machu Picchu and the Andes.",
    },
    {
        "id": 19,
        "name": "Buenos Aires",
        "region": "Argentina",
        "area": "South America",
        "budget_level": "low",
        "climate": "temperate",
        "tags": ["culture", "food", "nightlife"],
        "moods": ["culture", "food", "nightlife"],
        "avg_cost_per_day": 85,
        "description": "Tango, steak, and late, late nights.",
    },
    {
        "id": 20,
        "name": "Patagonia",
        "region": "Chile",
        "area": "South America",
        "budget_level": "high",
        "climate": "cool",
        "tags": ["nature", "adventure", "mountains"],
        "moods": ["adventure", "nature"],
        "avg_cost_per_day": 190,
        "description": "Granite towers, glaciers, and wild winds.",
    },
    {
        "id": 21,
        "name": "Tokyo",
        "region": "Japan",
        "area": "Japan",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["food", "culture", "nightlife"],
        "moods": ["food", "culture", "nightlife"],
        "avg_cost_per_day": 150,
        "description": "Neon districts and the best ramen on earth.",
    },
    {
        "id": 22,
        "name": "Osaka",
        "region": "Japan",
        "area": "Japan",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["food", "nightlife", "culture"],
        "moods": ["food", "nightlife"],
        "avg_cost_per_day": 110,
        "description": "Japan's street-food and comedy capital.",
    },
    {
        "id": 23,
        "name": "Maldives",
        "region": "Maldives",
        "area": "Islands",
        "budget_level": "high",
        "climate": "tropical",
        "tags": ["beach", "relaxation", "romance"],
        "moods": ["relaxation", "romance"],
        "avg_cost_per_day": 220,
        "description": "Overwater villas on impossibly blue water.",
    },
    {
        "id": 24,
        "name": "Hawaii",
        "region": "USA",
        "area": "Islands",
        "budget_level": "high",
        "climate": "tropical",
        "tags": ["beach", "nature", "adventure"],
        "moods": ["relaxation", "nature", "adventure"],
        "avg_cost_per_day": 200,
        "description": "Volcanoes, waterfalls, and world-class waves.",
    },
    {
        "id": 25,
        "name": "Phuket",
        "region": "Thailand",
        "area": "Islands",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["beach", "food", "nightlife"],
        "moods": ["relaxation", "beach", "nightlife"],
        "avg_cost_per_day": 70,
        "description": "Jungle-covered bays and neon beach bars.",
    },
    {
        "id": 26,
        "name": "Athens",
        "region": "Greece",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["history", "culture", "food"],
        "moods": ["culture", "history", "food"],
        "avg_cost_per_day": 105,
        "description": "The Acropolis, ancient agora, and sun-drenched tavernas.",
    },
    {
        "id": 27,
        "name": "Florence",
        "region": "Italy",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["art", "history", "romance"],
        "moods": ["culture", "history", "romance"],
        "avg_cost_per_day": 130,
        "description": "Renaissance masterpieces, bridges, and gelato.",
    },
    {
        "id": 28,
        "name": "Prague",
        "region": "Czechia",
        "area": "Europe",
        "budget_level": "low",
        "climate": "temperate",
        "tags": ["history", "culture", "nightlife"],
        "moods": ["culture", "history", "nightlife"],
        "avg_cost_per_day": 85,
        "description": "Castle-topped old town, bridges, and beer halls.",
    },
    {
        "id": 29,
        "name": "Bangkok",
        "region": "Thailand",
        "area": "Asia",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["food", "market", "nightlife"],
        "moods": ["food", "nightlife", "culture"],
        "avg_cost_per_day": 60,
        "description": "Street-food stalls, golden temples, and floating markets.",
    },
    {
        "id": 30,
        "name": "Singapore",
        "region": "Singapore",
        "area": "Asia",
        "budget_level": "high",
        "climate": "tropical",
        "tags": ["food", "nightlife", "culture"],
        "moods": ["food", "culture", "nightlife"],
        "avg_cost_per_day": 140,
        "description": "Hawker food, futuristic gardens, and rooftop bars.",
    },
    {
        "id": 31,
        "name": "Jaipur",
        "region": "India",
        "area": "Asia",
        "budget_level": "low",
        "climate": "desert",
        "tags": ["history", "culture", "market"],
        "moods": ["culture", "history"],
        "avg_cost_per_day": 55,
        "description": "Pink palaces, bazaars, and majestic forts.",
    },
    {
        "id": 32,
        "name": "Kerala",
        "region": "India",
        "area": "Asia",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["nature", "wellness", "relaxation"],
        "moods": ["nature", "relaxation", "wellness"],
        "avg_cost_per_day": 50,
        "description": "Backwater cruises, spice gardens, and Ayurveda.",
    },
    {
        "id": 33,
        "name": "Leh-Ladakh",
        "region": "India",
        "area": "Asia",
        "budget_level": "mid",
        "climate": "cool",
        "tags": ["mountains", "adventure", "nature"],
        "moods": ["adventure", "nature"],
        "avg_cost_per_day": 75,
        "description": "High-altitude passes, monasteries, and starry skies.",
    },
    {
        "id": 34,
        "name": "Kathmandu",
        "region": "Nepal",
        "area": "Asia",
        "budget_level": "low",
        "climate": "temperate",
        "tags": ["mountains", "adventure", "culture"],
        "moods": ["adventure", "culture", "history"],
        "avg_cost_per_day": 60,
        "description": "Gateways to Everest and centuries-old temples.",
    },
    {
        "id": 35,
        "name": "Cape Town",
        "region": "South Africa",
        "area": "Africa",
        "budget_level": "mid",
        "climate": "mediterranean",
        "tags": ["nature", "beach", "adventure"],
        "moods": ["nature", "adventure", "beach"],
        "avg_cost_per_day": 120,
        "description": "Table Mountain, penguins, and vineyard valleys.",
    },
    {
        "id": 36,
        "name": "Zanzibar",
        "region": "Tanzania",
        "area": "Africa",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["beach", "island", "relaxation"],
        "moods": ["relaxation", "beach", "culture"],
        "avg_cost_per_day": 70,
        "description": "Turquoise shallows, spice farms, and Stone Town.",
    },
    {
        "id": 37,
        "name": "Sydney",
        "region": "Australia",
        "area": "Oceania",
        "budget_level": "high",
        "climate": "temperate",
        "tags": ["beach", "food", "nightlife"],
        "moods": ["beach", "food", "nightlife"],
        "avg_cost_per_day": 160,
        "description": "Harbour icons, surf beaches, and buzzy cafés.",
    },
    {
        "id": 38,
        "name": "Cairns",
        "region": "Australia",
        "area": "Oceania",
        "budget_level": "mid",
        "climate": "tropical",
        "tags": ["beach", "diving", "nature"],
        "moods": ["adventure", "beach", "nature"],
        "avg_cost_per_day": 110,
        "description": "Gateway to the Great Barrier Reef and Daintree.",
    },
    {
        "id": 39,
        "name": "Dubai",
        "region": "UAE",
        "area": "Middle East",
        "budget_level": "high",
        "climate": "desert",
        "tags": ["nightlife", "market", "luxury"],
        "moods": ["nightlife", "culture", "relaxation"],
        "avg_cost_per_day": 180,
        "description": "Desert safaris, skyline views, and souks.",
    },
    {
        "id": 40,
        "name": "Costa Rica",
        "region": "Costa Rica",
        "area": "Central America",
        "budget_level": "mid",
        "climate": "tropical",
        "tags": ["nature", "wildlife", "adventure"],
        "moods": ["nature", "adventure", "relaxation"],
        "avg_cost_per_day": 100,
        "description": "Rainforests, volcanoes, and sloth spotting.",
    },
    {
        "id": 41,
        "name": "Manali",
        "region": "India",
        "area": "Asia",
        "budget_level": "low",
        "climate": "cool",
        "tags": ["mountains", "adventure", "nature"],
        "moods": ["adventure", "nature", "relaxation"],
        "avg_cost_per_day": 45,
        "description": "Snow-capped peaks, river valleys, and camping trails.",
    },
    {
        "id": 42,
        "name": "Goa",
        "region": "India",
        "area": "Asia",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["beach", "nightlife", "food"],
        "moods": ["beach", "relaxation", "nightlife"],
        "avg_cost_per_day": 50,
        "description": "Sunset beaches, seafood shacks, and beach parties.",
    },
    {
        "id": 43,
        "name": "Tromsø",
        "region": "Norway",
        "area": "Europe",
        "budget_level": "high",
        "climate": "cool",
        "tags": ["northern-lights", "nature", "adventure"],
        "moods": ["nature", "adventure"],
        "avg_cost_per_day": 185,
        "description": "Arctic city under the northern lights.",
    },
    {
        "id": 44,
        "name": "Banff",
        "region": "Canada",
        "area": "North America",
        "budget_level": "high",
        "climate": "cool",
        "tags": ["mountains", "nature", "lake"],
        "moods": ["nature", "adventure", "relaxation"],
        "avg_cost_per_day": 170,
        "description": "Turquoise lakes and towering Rocky peaks.",
    },
    {
        "id": 45,
        "name": "Lake Como",
        "region": "Italy",
        "area": "Europe",
        "budget_level": "high",
        "climate": "mediterranean",
        "tags": ["romance", "nature", "relaxation"],
        "moods": ["romance", "relaxation", "nature"],
        "avg_cost_per_day": 175,
        "description": "Lakefront villas and picture-perfect villages.",
    },
    {
        "id": 46,
        "name": "Galle",
        "region": "Sri Lanka",
        "area": "Asia",
        "budget_level": "low",
        "climate": "tropical",
        "tags": ["beach", "history", "food"],
        "moods": ["relaxation", "culture", "food"],
        "avg_cost_per_day": 65,
        "description": "Colonial forts, surf beaches, and spice country.",
    },
    {
        "id": 47,
        "name": "Seychelles",
        "region": "Seychelles",
        "area": "Islands",
        "budget_level": "high",
        "climate": "tropical",
        "tags": ["beach", "romance", "relaxation"],
        "moods": ["relaxation", "romance", "beach"],
        "avg_cost_per_day": 210,
        "description": "Granite boulders, white sand, and calm lagoons.",
    },
    {
        "id": 48,
        "name": "Nairobi",
        "region": "Kenya",
        "area": "Africa",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["wildlife", "adventure", "nature"],
        "moods": ["adventure", "nature", "culture"],
        "avg_cost_per_day": 95,
        "description": "City to savannah — lions an hour away.",
    },
    {
        "id": 49,
        "name": "Dublin",
        "region": "Ireland",
        "area": "Europe",
        "budget_level": "mid",
        "climate": "temperate",
        "tags": ["culture", "food", "nightlife"],
        "moods": ["culture", "nightlife", "food"],
        "avg_cost_per_day": 115,
        "description": "Pubs, live music, and castle-topped cliffs nearby.",
    },
    {
        "id": 50,
        "name": "Chefchaouen",
        "region": "Morocco",
        "area": "Africa",
        "budget_level": "low",
        "climate": "temperate",
        "tags": ["market", "culture", "history"],
        "moods": ["culture", "relaxation"],
        "avg_cost_per_day": 55,
        "description": "Blue-washed lanes in the Rif mountains.",
    },
]
